### PR TITLE
Add example looking glass EEPROM

### PR DESCRIPTION
**Pull request by ianrrees**
Thanks for putting this all together!  I had some hurdles in getting the EEPROM extraction to work, was thinking that it might be helpful to include an example EEPROM so that others might be able to get started quicker?

I only have access to the one LG, so am not sure how important it is to get the correct calibration...

### CODE REVIEW

**Comment by lonetech** [comment]
I don't have much statistics, but that certainly looked garbled with mine. The calibration data is rather individual per device, hence the USB storage of it.

**Comment by ianrrees** [comment]
Interesting, thanks for that.

How did you get your Python hidapi bindings?  I'm running Ubuntu 18.04 currently, and there are several options between apt and pip - none of the ones I tried seemed to work well.

**Comment by lonetech** [comment]
I've done my testing on Debian and NixOS, and I've read using both python-hidapi and python-hid, both of which wrap the hidapi library, which in turn uses either libusb or hidraw. I too had varied success, though the combination using hidraw never failed (except if run after the libusb variant, which detaches the hid driver). Then I rebooted into Windows and found it wouldn't recognize the Looking Glass at all on that USB port. YMMV.

**Comment by ianrrees** [comment]
Ahh, I see.  Some of the problems I was bumping in to were likely caused by switching around the Python HID libraries then.

I've started on a Rust library for Looking Glass, so far it provides essentially the same functionality as lgeeprom.py using libhidapi (which ends up being the libusb variant on Ubuntu 18.04 if installed the obvious way).  At this stage, it's mainly just an exercise for me to practice Rust, but does seem to work reliably on my system.

**Pull request closed without merging**
